### ISSUE TITLE
Index out of range when running PUSHBACK

### ISSUE THREAD

**Issue by jimmyyou** [utah-scs/splinter#25]
I got this error when trying to run the PUSHBACK workload

> thread 'INFO:splinter::dispatch: Received many responses...sched-7
' panicked at 'index 377 out of range for slice of length 278', INFO:pushback: PUSHBACK/rustc/XXXX/src/libcore/slice/mod.rs

Configuration used:
```
key_size = 30
value_size = 100
num_aggr = 2
order = 1000
```

**Comment by ankitbhrdwj** [comment]
@jimmyyou The server moves the extension invocation back to the client with the rwset and the client parses that rwset. The error is occurring because the client is trying to access the byte which is not in the rwset.

The current rwset size is 278 = 2 * (keylen + val len) = 260 + 18 byte metadata, and the program is trying to access 377th byte. The client parses the rwset here - https://github.com/utah-scs/splinter/blob/7382303182863a3f2ca575a3c421fdf4361885de/splinter/src/bin/client/pushback.rs#L478


Now the reason this is happening because the client is under the impression that you are running some different extension because the feature flag in the toml file is set https://github.com/utah-scs/splinter/blob/7382303182863a3f2ca575a3c421fdf4361885de/splinter/Cargo.toml#L90 Clear both the features and try again.
